function Hd = notch_filter
%NOTCH_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 21-Sep-2023 14:33:46

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
BW     = 10;  % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df1sos(b, a);

% [EOF]
